region = 1
region = 2
region = 3
region = 4
region = 5
region = 6
region = 7
region = 8
region = 9
region = 10
region = 11
region = 12
region = 13
region = 14
region = 15
region = 16
region = 17
region = 18
region = 19
region = 20
region = 21
region = 22
region = 23
region = 24
region = 25
region = 26
region = 27
region = 28
region = 29
region = 30
region = 31
region = 32
region = 33
region = 34
region = 35
region = 36
region = 37
region = 38
region = 39
region = 40
region = 41
region = 42
region = 43
region = 44
region = 45
region = 46
region = 47
region = 48
region = 49
region = 50
region = 51
region = 52
Traceback (most recent call last):
  File "converttoh5.py", line 61, in <module>
    img_sz = read_sz(lp,hid,RA)
  File "converttoh5.py", line 28, in read_sz
    data = fits.getdata(path+region+file)
  File "/usr/local/lib/python3.8/dist-packages/astropy/io/fits/convenience.py", line 194, in getdata
    hdulist, extidx = _getext(filename, mode, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/astropy/io/fits/convenience.py", line 1054, in _getext
    hdulist = fitsopen(filename, mode=mode, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/astropy/io/fits/hdu/hdulist.py", line 164, in fitsopen
    return HDUList.fromfile(name, mode, memmap, save_backup, cache,
  File "/usr/local/lib/python3.8/dist-packages/astropy/io/fits/hdu/hdulist.py", line 401, in fromfile
    return cls._readfrom(fileobj=fileobj, mode=mode, memmap=memmap,
  File "/usr/local/lib/python3.8/dist-packages/astropy/io/fits/hdu/hdulist.py", line 1052, in _readfrom
    fileobj = _File(fileobj, mode=mode, memmap=memmap, cache=cache)
  File "/usr/local/lib/python3.8/dist-packages/astropy/utils/decorators.py", line 535, in wrapper
    return function(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/astropy/io/fits/file.py", line 175, in __init__
    self._open_filename(fileobj, mode, overwrite)
  File "/usr/local/lib/python3.8/dist-packages/astropy/io/fits/file.py", line 564, in _open_filename
    self._file = fileobj_open(self.name, IO_FITS_MODES[mode])
  File "/usr/local/lib/python3.8/dist-packages/astropy/io/fits/util.py", line 392, in fileobj_open
    return open(filename, mode, buffering=0)
FileNotFoundError: [Errno 2] No such file or directory: '/data7/users/deandres/newML2/SZ/NewMDCLUSTER_0052/snap_125-TT-cl-125000000000001-ra-14.fits'
